name: CI Script
on: [push]

jobs:
  # Deploy Process
  deploy:
    runs-on: ubuntu-18.04 
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UPSTOCK_DEV_SERVER_IP }}
        username: "root"
        key: ${{ secrets.UPSTOCK_DEV_SERVER_PRIVATE_KEY }}
        port: 22
        script: /var/www/upstock-environment/test
